## list developers


GET http://localhost:3000/developers


### get developer


GET http://localhost:3000/developers/3

### create developer


POST http://localhost:3000/developers
Content-Type: application/json

{
    "name":"john doe",
    "email":"john.doe@acme.com",
    "dateOfBirth":"1990-01-01"
}
### update developer


PATCH  http://localhost:3000/developers/3
Content-Type: application/json

{
        "email":"john.doe@acme.com",

}
### delete developer


DELETE  http://localhost:3000/developers/3